### ISSUE TITLE
EPIC: New UI

### ISSUE THREAD

**Issue by Wingysam** [GalaxyRoblox/Issues-Public#98]
Plan, design, implement, test, and release a new UI for Galaxy that brings its look into 2024 and beyond.

```[tasklist]
### Components
- [x] https://github.com/GalaxyRoblox/Issues-Staff/issues/47
- [x] https://github.com/GalaxyRoblox/Issues-Staff/issues/48
- [x] https://github.com/GalaxyRoblox/Issues-Staff/issues/49
- [x] https://github.com/GalaxyRoblox/Issues-Staff/issues/50
- [ ] https://github.com/GalaxyRoblox/Issues-Staff/issues/51
- [ ] https://github.com/GalaxyRoblox/Issues-Staff/issues/52
- [ ] https://github.com/GalaxyRoblox/Issues-Staff/issues/53
- [ ] https://github.com/GalaxyRoblox/Issues-Staff/issues/54
- [ ] https://github.com/GalaxyRoblox/Issues-Staff/issues/55
- [ ] https://github.com/GalaxyRoblox/Issues-Staff/issues/56
- [ ] https://github.com/GalaxyRoblox/Issues-Staff/issues/57
- [ ] https://github.com/GalaxyRoblox/Issues-Staff/issues/58
- [ ] https://github.com/GalaxyRoblox/Issues-Staff/issues/59
- [ ] https://github.com/GalaxyRoblox/Issues-Staff/issues/60
- [ ] https://github.com/GalaxyRoblox/Issues-Staff/issues/61
- [ ] https://github.com/GalaxyRoblox/Issues-Staff/issues/62
- [ ] https://github.com/GalaxyRoblox/Issues-Staff/issues/63
- [ ] https://github.com/GalaxyRoblox/Issues-Staff/issues/64
- [ ] https://github.com/GalaxyRoblox/Issues-Staff/issues/65
- [ ] https://github.com/GalaxyRoblox/Issues-Staff/issues/66
```
